/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : PDDL.g
 *     -                            On : 2016-09-26 11:44:47
 *     -                 for the lexer : PDDLLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
PDDLLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pPDDLLexer, which is returned from a call to PDDLLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pPDDLLexer are  as follows:
 *
 *  - 
 void
      pPDDLLexer->T__54(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__55(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__56(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__57(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__58(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__59(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__60(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__61(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__62(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__63(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__64(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__65(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__66(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__67(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__68(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__69(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__70(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__71(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__72(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__73(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__74(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__75(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__76(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__77(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__78(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__79(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__80(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__81(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__82(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__83(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__84(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__85(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__86(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__87(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__88(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__89(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__90(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__91(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__92(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__93(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__94(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__95(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__96(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__97(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__98(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__99(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__100(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__101(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__102(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__103(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__104(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__105(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__106(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__107(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__108(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__109(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__110(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__111(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__112(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__113(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__114(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__115(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__116(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__117(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__118(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__119(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->T__120(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->REQUIRE_KEY(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->NAME(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->LETTER(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->ANY_CHAR(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->VARIABLE(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->NUMBER(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->DIGIT(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->LINE_COMMENT(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->WHITESPACE(pPDDLLexer)
 *  - 
 void
      pPDDLLexer->Tokens(pPDDLLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_PDDLLexer_H
#define _PDDLLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct PDDLLexer_Ctx_struct PDDLLexer, * pPDDLLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
PDDLLexer

 */
struct PDDLLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__54)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__89)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__90)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__91)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__92)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__93)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__94)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__95)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__96)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__97)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__98)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__99)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__100)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__101)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__102)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__103)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__104)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__105)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__106)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__107)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__108)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__109)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__110)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__111)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__112)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__113)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__114)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__115)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__116)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__117)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__118)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__119)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mT__120)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mREQUIRE_KEY)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mNAME)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mLETTER)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mANY_CHAR)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mVARIABLE)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mNUMBER)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mDIGIT)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMENT)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mWHITESPACE)	(struct PDDLLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct PDDLLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct PDDLLexer_Ctx_struct * ctx);
    void	    (*free)   (struct PDDLLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pPDDLLexer PDDLLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pPDDLLexer PDDLLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define T__101      101
#define T__102      102
#define T__103      103
#define T__104      104
#define T__105      105
#define T__106      106
#define T__107      107
#define T__108      108
#define T__109      109
#define T__110      110
#define T__111      111
#define T__112      112
#define T__113      113
#define T__114      114
#define T__115      115
#define T__116      116
#define T__117      117
#define T__118      118
#define T__119      119
#define T__120      120
#define ACTION      4
#define AND_EFFECT      5
#define AND_GD      6
#define ANY_CHAR      7
#define ASSIGN_EFFECT      8
#define BINARY_OP      9
#define COMPARISON_GD      10
#define CONSTANTS      11
#define CONSTRAINT      12
#define DIGIT      13
#define DOMAIN      14
#define DOMAIN_NAME      15
#define DURATIVE_ACTION      16
#define EFFECT      17
#define EITHER_TYPE      18
#define EXISTS_GD      19
#define FORALL_EFFECT      20
#define FORALL_GD      21
#define FUNCTIONS      22
#define FUNC_HEAD      23
#define GOAL      24
#define IMPLY_GD      25
#define INIT      26
#define INIT_AT      27
#define INIT_EQ      28
#define LETTER      29
#define LINE_COMMENT      30
#define NAME      31
#define NOT_EFFECT      32
#define NOT_GD      33
#define NOT_PRED_INIT      34
#define NUMBER      35
#define OBJECTS      36
#define OR_GD      37
#define PRECONDITION      38
#define PREDICATES      39
#define PRED_HEAD      40
#define PRED_INST      41
#define PROBLEM      42
#define PROBLEM_CONSTRAINT      43
#define PROBLEM_DOMAIN      44
#define PROBLEM_METRIC      45
#define PROBLEM_NAME      46
#define REQUIREMENTS      47
#define REQUIRE_KEY      48
#define TYPES      49
#define UNARY_MINUS      50
#define VARIABLE      51
#define WHEN_EFFECT      52
#define WHITESPACE      53
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for PDDLLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
